[project]
name = "example-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.9.9",
]

[tool.uv.workspace]
members = ["SCRIPTS", "SCRIPTS/docs/hello-world"]
